name: PR Build for Emnos Assistant (emnos-assistant)

concurrency:
  group: pr
  cancel-in-progress: false

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  build:
    name: Run lint and tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4.1.1

  lint-dockerfile:
    name: Lint dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Lint the dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./emnos-tools/dockerfile